// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240708180045_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6012),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6025),
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6026),
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("Entity.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6360),
                            Name = "Product 1",
                            Price = 100.0m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6361),
                            Name = "Product 2",
                            Price = 200.0m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6362),
                            Name = "Product 3",
                            Price = 150.0m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6363),
                            Name = "Product 4",
                            Price = 250.0m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6364),
                            Name = "Product 5",
                            Price = 300.0m,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Entity.Model.ProductDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductDetails", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6239),
                            Description = "Latest model smartphone with advanced features",
                            ProductId = 1,
                            Stock = 150
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6240),
                            Description = "High-performance laptop for gaming and work",
                            ProductId = 2,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6240),
                            Description = "Energy-efficient refrigerator with spacious compartments",
                            ProductId = 3,
                            Stock = 75
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6241),
                            Description = "Front-loading washing machine with quick wash feature",
                            ProductId = 4,
                            Stock = 50
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6242),
                            Description = "Best-selling fiction novel",
                            ProductId = 5,
                            Stock = 200
                        });
                });

            modelBuilder.Entity("Entity.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6450),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6450),
                            RoleName = "User"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(6451),
                            RoleName = "Guest"
                        });
                });

            modelBuilder.Entity("Entity.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("FirstName", "LEN(FirstName) >= 3");

                            t.HasCheckConstraint("LastName", "LEN(LastName) >= 3");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(7064),
                            Email = "ege.erbilen@example.com",
                            FirstName = "Ege",
                            LastName = "Erbilen",
                            Password = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(7084),
                            Email = "ece.doe@example.com",
                            FirstName = "Ece",
                            LastName = "Doe",
                            Password = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 7, 8, 21, 0, 45, 37, DateTimeKind.Local).AddTicks(7111),
                            Email = "ahmet.yilmaz@example.com",
                            FirstName = "Ahmet",
                            LastName = "Yılmaz",
                            Password = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
                        });
                });

            modelBuilder.Entity("Entity.Model.UserFavoritesProducts", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersFavoritesProducts", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            UserId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            UserId = 2,
                            ProductId = 2
                        },
                        new
                        {
                            UserId = 2,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("Entity.Model.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsersRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Entity.Model.Product", b =>
                {
                    b.HasOne("Entity.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Model.ProductDetails", b =>
                {
                    b.HasOne("Entity.Model.Product", "Product")
                        .WithOne("ProductDetails")
                        .HasForeignKey("Entity.Model.ProductDetails", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entity.Model.UserFavoritesProducts", b =>
                {
                    b.HasOne("Entity.Model.Product", "Product")
                        .WithMany("UserFavoritesProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.User", "User")
                        .WithMany("UserFavoritesProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Model.UserRole", b =>
                {
                    b.HasOne("Entity.Model.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Model.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entity.Model.Product", b =>
                {
                    b.Navigation("ProductDetails")
                        .IsRequired();

                    b.Navigation("UserFavoritesProducts");
                });

            modelBuilder.Entity("Entity.Model.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Entity.Model.User", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("UserFavoritesProducts");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
